<script setup>
import { masterConfig } from '../../utils/master-config.js'
import { money, dateLabel, initials, today } from '#shared/utils/format.js'
import { ROLE_LABELS } from '#shared/constants/index.js'
import { DateTime } from 'luxon'
const props=defineProps({resource:String});const config=masterConfig[props.resource]
const {isOwner,isOffice,canAssign,isLocationAdmin}=useAuth()
const canCreate=computed(()=>props.resource==='customers'?isOffice.value:['schedules','therapists'].includes(props.resource)?canAssign.value:isOwner.value)
const {data,refresh,error}=await useFetch('/api/'+props.resource,{default:()=>[]})
const search=ref('');const page=ref(1);const date=ref(today());const view=ref('day');const location=ref('');const therapist=ref('')
const rows=computed(()=>data.value.filter(row=>{
 if(search.value&&!Object.values(row).filter(v=>typeof v==='string').join(' ').toLowerCase().includes(search.value.toLowerCase()))return false
 if(props.resource==='schedules') {const end=view.value==='week'?DateTime.fromISO(date.value).plus({days:6}).toISODate():date.value;if(row.scheduleDate<date.value||row.scheduleDate>end)return false;if(location.value&&row.locationId!==Number(location.value))return false;if(therapist.value&&row.therapistId!==Number(therapist.value))return false}
 return true
}))
const visible=computed(()=>rows.value.slice((page.value-1)*10,page.value*10))
const locations=computed(()=>[...new Map(data.value.map(s=>[s.locationId,s.locationName])).entries()]);const therapists=computed(()=>[...new Map(data.value.map(s=>[s.therapistId,s.therapistName])).entries()])
watch([search,date,view,location,therapist],()=>page.value=1)
function cell(row,key){if(key==='createdAt'||key==='scheduleDate')return dateLabel(row[key]);if(key==='price')return money(row[key]);if(key==='durationMinutes')return row[key]+' menit';if(key==='locations')return row.locations.map(l=>l.name).join(', ');if(key==='role')return ROLE_LABELS[row.role];if(['startTime','endTime'].includes(key))return row[key].slice(0,5);return row[key]||'—'}
</script><template><div><LayoutPageHeader :title="config.title" :description="config.description" eyebrow="MANAGEMENT"><UiButton v-if="canCreate" :to="'/'+resource+'/new'"><UiIcon name="plus" :size="17" />Tambah {{ config.singular }}</UiButton></LayoutPageHeader><div v-if="resource==='services'" class="service-grid"><NuxtLink v-for="s in data.filter(s=>s.isActive)" :key="s.id" :to="'/services/'+s.id" class="panel service-card"><div class="service-card-icon"><UiIcon name="services" :size="26" /></div><h3>{{ s.name }}</h3><p>{{ s.description }}</p><div><span><UiIcon name="clock" :size="15" />{{ s.durationMinutes }} menit</span><strong>{{ money(s.price) }}</strong></div></NuxtLink></div><section class="panel"><div class="filter-bar"><div class="search-control"><UiIcon name="search" :size="17" /><input v-model="search" :placeholder="'Cari '+config.singular+'…'" :aria-label="'Cari '+config.singular" /></div><span class="muted">{{ rows.length }} {{ config.singular }}</span><template v-if="resource==='schedules'"><input v-model="date" type="date" aria-label="Tanggal jadwal" /><select v-model="view" aria-label="Tampilan jadwal"><option value="day">Harian</option><option value="week">Mingguan</option></select><select v-model="location" aria-label="Lokasi jadwal"><option value="">Semua lokasi</option><option v-for="[id,name] in locations" :key="id" :value="id">{{ name }}</option></select><select v-model="therapist" aria-label="Therapist jadwal"><option value="">Semua therapist</option><option v-for="[id,name] in therapists" :key="id" :value="id">{{ name }}</option></select></template></div><p v-if="error" class="error-message">{{ error.data?.statusMessage }} <button @click="refresh">Coba lagi</button></p><div class="table-wrap"><table><thead><tr><th v-for="[key,label] in config.columns" :key="key">{{ label }}</th><th /></tr></thead><tbody><tr v-for="row in visible" :key="row.id"><td v-for="([key,label],i) in config.columns" :key="key"><NuxtLink v-if="i===0" :to="'/'+resource+'/'+row.id" class="customer-cell"><span class="avatar pastel">{{ initials(row.name||row.therapistName) }}</span><strong>{{ cell(row,key) }}</strong></NuxtLink><UiBadge v-else-if="key==='status'" :status="row.status" /><span v-else-if="key==='isActive'" :class="['badge',row.isActive?'badge-green':'badge-gray']"><span class="badge-dot" />{{ row.isActive?'Aktif':'Nonaktif' }}</span><span v-else>{{ cell(row,key) }}</span></td><td><NuxtLink :to="'/'+resource+'/'+row.id+(canCreate&&row.canManage!==false?'/edit':'')" class="icon-button" :aria-label="(canCreate&&row.canManage!==false?'Edit ':'Lihat ')+(row.name||row.therapistName)"><UiIcon :name="canCreate&&row.canManage!==false?'edit':'right'" :size="16" /></NuxtLink></td></tr></tbody></table><UiEmptyState v-if="!rows.length" :icon="config.icon" :title="'Belum ada '+config.singular" message="Tambah data atau sesuaikan pencarian Anda." /></div><UiPagination v-model:page="page" :total="rows.length" /></section></div></template>