<script setup>
import UiMoneyInput from '~/components/ui/MoneyInput.vue'
import { masterConfig } from '../../utils/master-config.js'
import { today } from '#shared/utils/format.js'
const props=defineProps({resource:String,id:String});const config=masterConfig[props.resource]
const {toast,error}=useFeedback();const {isOwner,isOffice,canAssign,isLocationAdmin}=useAuth()
const allowed=props.resource==='customers'?isOffice.value:['schedules','therapists'].includes(props.resource)?canAssign.value:isOwner.value
if(!allowed)await navigateTo('/'+props.resource)
const record=props.id?await useRequestFetch()('/api/'+props.resource+'/'+props.id):null
if(record?.canManage===false&&isLocationAdmin.value)await navigateTo('/therapists/'+props.id)
const form=reactive(Object.fromEntries(config.fields.map(f=>[f.key,record?.[f.key] ?? f.default ?? (f.type==='date'?today():'')])))
if(props.resource==='schedules'&&record){form.startTime=record.startTime.slice(0,5);form.endTime=record.endTime.slice(0,5)}
const sources=reactive({locations:[],therapists:[]})
for(const source of new Set(config.fields.map(f=>f.source).filter(Boolean))){sources[source]=isLocationAdmin.value&&source==='locations'?(await useRequestFetch()('/api/therapists/options')).locations:await useRequestFetch()('/api/'+source)}
const busy=ref(false);const message=ref('')
watch(()=>form.locationId, id=>{if(props.resource==='services'&&record){const price=record.prices.find(p=>p.isActive&&p.locationId===id);form.price=Number(price?.price || 0)}})
async function submit(){busy.value=true;message.value='';try{const body={...form};if('password' in body&&!body.password)delete body.password;const row=await $fetch('/api/'+props.resource+(props.id?'/'+props.id:''),{method:props.id?'PATCH':'POST',body});toast('Data berhasil disimpan');await navigateTo('/'+props.resource+'/'+row.id)}catch(e){message.value=error(e)}finally{busy.value=false}}
</script><template><div><LayoutPageHeader :title="(id?'Edit ':'Tambah ')+config.singular" :description="id?'Perbarui informasi dengan teliti.':'Lengkapi informasi untuk memulai.'" eyebrow="MANAGEMENT" /><form class="panel form-panel master-form" @submit.prevent="submit"><div class="form-grid"><template v-for="f in config.fields" :key="f.key"><label v-if="f.type==='checkbox'" class="checkbox-label full"><input v-model="form[f.key]" type="checkbox" />{{ f.label }}</label><fieldset v-else-if="f.type==='multi'" class="full"><legend>{{ f.label }}</legend><div class="checkbox-group"><label v-for="s in sources[f.source]" :key="s.id" class="checkbox-label"><input v-model="form[f.key]" type="checkbox" :value="s.id" />{{ s.name }}</label></div></fieldset><label v-else :class="{full:f.type==='textarea'}">{{ f.label }}<span v-if="f.required" class="required">*</span><textarea v-if="f.type==='textarea'" v-model="form[f.key]" rows="3" /><select v-else-if="f.type==='select'" v-model="form[f.key]" :aria-label="f.label" :required="f.required" :disabled="!!id&&resource==='schedules'&&f.key==='therapistId'"><option v-if="f.source" :value="f.empty?null:''" :disabled="!f.empty">{{ f.empty||'Pilih '+f.label.toLowerCase() }}</option><option v-for="s in f.source?sources[f.source]:[]" :key="s.id" :value="s.id">{{ s.name }}</option><option v-for="[value,label] in f.options||[]" :key="value" :value="value">{{ label }}</option></select><UiMoneyInput v-else-if="f.type==='money'" v-model="form[f.key]" :aria-label="f.label" :required="f.required" :min="f.min??0" :max="f.max??1000000000" /><input v-else v-model="form[f.key]" :type="f.type||'text'" :required="f.required||(f.key==='password'&&!id)" :min="f.min" :max="f.max" :step="f.step" :minlength="f.minlength" :disabled="!!id&&resource==='schedules'&&f.key==='scheduleDate'" :autocomplete="f.key==='password'?'new-password':'off'" /><small v-if="f.key==='password'&&id" class="form-hint">Kosongkan untuk mempertahankan password.</small><small v-if="resource==='services'&&f.key==='locationId'" class="form-hint">Pilih cabang untuk mengatur harga khusus; harga umum menjadi fallback.</small></label></template></div><p v-if="resource==='users'&&form.role==='THERAPIST'" class="note-box">Untuk akun therapist baru, gunakan menu Therapists agar profil dan lokasi kerja ikut dibuat.</p><p v-if="message" role="alert" class="error-message">{{ message }}</p><div class="form-actions"><UiButton :to="'/'+resource" variant="secondary">Batal</UiButton><UiButton type="submit" :loading="busy">Simpan {{ config.singular }}<UiIcon name="check" :size="16" /></UiButton></div></form></div></template>