<script setup>
import { dateLabel, today } from '#shared/utils/format.js'
const props=defineProps({therapist:Object})
const {data:schedules,refresh,error}=await useFetch(`/api/therapists/${props.therapist.id}/schedules`,{default:()=>[]})
const {toast,error:formatError}=useFeedback()
const open=ref(false),editingId=ref(null),busy=ref(false),message=ref('')
const form=reactive({therapistId:props.therapist.id,locationId:props.therapist.locationIds[0],scheduleDate:today(),startTime:'08:00',endTime:'22:00',status:'AVAILABLE',notes:''})
function edit(row){editingId.value=row?.id||null;Object.assign(form,{therapistId:props.therapist.id,locationId:row?.locationId||props.therapist.locationIds[0],scheduleDate:row?.scheduleDate||today(),startTime:row?.startTime.slice(0,5)||'08:00',endTime:row?.endTime.slice(0,5)||'22:00',status:row?.status||'AVAILABLE',notes:row?.notes||''});message.value='';open.value=true}
async function save(){busy.value=true;message.value='';try{await $fetch(`/api/therapists/${props.therapist.id}/schedules`+(editingId.value?'/'+editingId.value:''),{method:editingId.value?'PATCH':'POST',body:form});toast('Jadwal therapist tersimpan');open.value=false;await refresh()}catch(e){message.value=formatError(e)}finally{busy.value=false}}
const page=ref(1)
const visible=computed(()=>[...schedules.value].sort((a,b)=>b.scheduleDate.localeCompare(a.scheduleDate)).slice((page.value-1)*10,page.value*10))
</script>
<template>
  <section class="panel mt-5"><div class="panel-heading"><div><h2>Jadwal therapist</h2><p class="muted">Atur jam kerja, libur, dan cuti untuk lokasi Anda.</p></div><UiButton @click="edit()">Tambah jadwal</UiButton></div><p v-if="error" class="error-message">Jadwal gagal dimuat.</p><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Lokasi</th><th>Jam kerja</th><th>Status</th><th /></tr></thead><tbody><tr v-for="row in visible" :key="row.id"><td>{{ dateLabel(row.scheduleDate) }}</td><td>{{ row.locationName }}</td><td>{{ row.startTime.slice(0,5) }} – {{ row.endTime.slice(0,5) }}</td><td><UiBadge :status="row.status" /></td><td><button class="text-link" :aria-label="'Edit jadwal '+row.scheduleDate" @click="edit(row)">Edit jadwal</button></td></tr></tbody></table><UiEmptyState v-if="!schedules.length" title="Belum ada jadwal" message="Tambahkan jadwal kerja therapist." /></div><UiPagination v-model:page="page" :total="schedules.length" /></section>
  <UiModal :open="open" :title="editingId?'Edit jadwal therapist':'Tambah jadwal therapist'" @close="open=false"><form @submit.prevent="save"><label>Lokasi kerja<select v-model="form.locationId" required><option v-for="location in therapist.locations" :key="location.locationId" :value="location.locationId">{{ location.name }}</option></select></label><label>Tanggal jadwal<input v-model="form.scheduleDate" type="date" :disabled="!!editingId" required /></label><div class="form-grid"><label>Jam mulai<input v-model="form.startTime" type="time" required /></label><label>Jam selesai<input v-model="form.endTime" type="time" required /></label></div><label>Status jadwal<select v-model="form.status"><option value="AVAILABLE">Tersedia</option><option value="OFF">Libur</option><option value="LEAVE">Cuti</option></select></label><label>Catatan<textarea v-model="form.notes" rows="2" /></label><p v-if="message" class="error-message" role="alert">{{ message }}</p><div class="modal-actions"><UiButton variant="secondary" @click="open=false">Batal</UiButton><UiButton type="submit" :loading="busy">Simpan jadwal</UiButton></div></form></UiModal>
</template>
