import { test, expect } from '@playwright/test'
import sharp from 'sharp'

test('owner can save app name, logo and favicon across public pages and reloads', async ({ page, browser }) => {
  await page.goto('/login')
  await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready', 'true')
  await page.getByLabel('Email', { exact: true }).fill('owner@serene.local')
  await page.getByLabel('Password', { exact: true }).fill(process.env.SEED_PASSWORD)
  await page.getByRole('button', { name: 'Masuk', exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  const original = await (await page.request.get('/api/settings/branding')).json()
  const publicContext = await browser.newContext()
  const publicPage = await publicContext.newPage()
  try {
    await page.goto('/settings')
    await page.getByLabel('Nama aplikasi', { exact: true }).fill('Lotus Wellness Test')
    await page.getByLabel('Logo aplikasi', { exact: true }).setInputFiles('public/icons/icon-192.png')
    await page.getByRole('button', { name: 'Gunakan logo sebagai favicon', exact: true }).click()
    const saved = page.waitForResponse(r => r.url().endsWith('/api/settings/branding') && r.request().method() === 'PATCH')
    await page.getByRole('button', { name: 'Simpan identitas aplikasi', exact: true }).click()
    expect((await saved).status()).toBe(200)
    await expect(page).toHaveTitle('Lotus Wellness Test')
    await expect(page.locator('.sidebar .brand')).toContainText('Lotus Wellness Test')
    await expect(page.locator('.sidebar .brand img')).toHaveAttribute('src', /branding-icon\/logo\?v=/)
    await expect(page.locator('link[rel="icon"]')).toHaveCount(1)
    await expect(page.locator('link[rel="icon"]')).toHaveAttribute('href', /branding-icon\/favicon\?v=/)
    await page.reload()
    await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready', 'true')
    await expect(page.getByLabel('Nama aplikasi', { exact: true })).toHaveValue('Lotus Wellness Test')
    const stored = await (await page.request.get('/api/settings/branding')).json()
    expect(stored.logo).toMatch(/^data:image\/png;base64,/)
    expect(stored.favicon).toBe(stored.logo)
    await page.screenshot({ path: 'artifacts/branding-settings-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
    await page.screenshot({ path: 'artifacts/branding-settings-mobile.png', fullPage: true, animations: 'disabled' })
    for (const path of ['/login', '/book', '/']) {
      await publicPage.goto(path)
      await expect(publicPage.locator('.brand')).toContainText('Lotus Wellness Test')
      await expect(publicPage).toHaveTitle(/Lotus Wellness Test/)
    }
    const manifest = await (await publicPage.request.get('/api/public/branding-manifest')).json()
    expect(manifest.name).toBe('Lotus Wellness Test')
    for (const icon of manifest.icons) {
      const response = await publicPage.request.get(icon.src)
      expect(response.status()).toBe(200)
      const metadata = await sharp(await response.body()).metadata()
      expect(`${metadata.width}x${metadata.height}`).toBe(icon.sizes)
    }
    expect((await publicPage.request.patch('/api/settings/branding', { data: original })).status()).toBe(401)
    expect((await publicPage.request.get('/api/settings/branding')).status()).toBe(401)
    const unauthorizedLogin = await publicPage.request.post('/api/auth/login', { data: { email: 'ayu@serene.local', password: process.env.SEED_PASSWORD } })
    expect(unauthorizedLogin.status()).toBe(200)
    expect((await publicPage.request.patch('/api/settings/branding', { data: original })).status()).toBe(403)
    expect((await publicPage.request.get('/api/settings/branding')).status()).toBe(403)
    await page.setViewportSize({ width: 1440, height: 1050 })
    await page.getByRole('button', { name: 'Gunakan logo bawaan', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Gunakan logo bawaan', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Gunakan favicon bawaan', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Gunakan favicon bawaan', exact: true })).toHaveCount(0)
    const reset = page.waitForResponse(r => r.url().endsWith('/api/settings/branding') && r.request().method() === 'PATCH')
    await page.getByRole('button', { name: 'Simpan identitas aplikasi', exact: true }).click()
    expect((await reset).status()).toBe(200)
    await expect(page.locator('link[rel="icon"]')).toHaveAttribute('href', '/favicon.svg?v=3')
    await expect(page.locator('.sidebar .brand img')).toHaveAttribute('src', '/logo.svg')
  } finally {
    expect((await page.request.patch('/api/settings/branding', { data: original })).status()).toBe(200)
    await publicContext.close()
  }
})
