import { test, expect } from '@playwright/test'
import { elapseTreatment } from '../../scripts/test-support/treatment.js'
import { db,pool } from '../../server/database/index.js'
import * as s from '../../server/database/schema/index.js'
import { eq, inArray, sql } from 'drizzle-orm'
const password=process.env.SEED_PASSWORD
async function mockMapTiles(context) {
 await context.route(/^https:\/\/tile\.openstreetmap\.org\//, route=>route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#e8efdf"/><path d="M0 64h256M64 0v256" stroke="#fff" stroke-width="5"/></svg>'}))
}
test.beforeEach(async({context})=>{await mockMapTiles(context)})
async function login(page,email='owner@serene.local') {
 await page.goto('/login')
 await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 await page.getByLabel('Email',{exact:true}).fill(email)
 await page.getByLabel('Password',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Masuk',exact:true}).click()
 await expect(page).toHaveURL(email==='ayu@serene.local'?/\/therapist$/:/\/dashboard$/)
}
test('public HTML demo documentation is reachable from booking and works on mobile',async({page})=>{
 await page.goto('/book');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 await expect(page.getByRole('link',{name:'Staff login'})).toHaveCount(0)
 await page.getByRole('link',{name:'Panduan',exact:true}).click();await expect(page).toHaveURL(/\/dokumentasi\.html$/)
 await expect(page.getByRole('heading',{name:'Satu panduan untuk setiap alur pelayanan.'})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible()
 await page.getByRole('navigation',{name:'Daftar isi'}).getByRole('link',{name:'Harga & pembayaran'}).click();await expect(page).toHaveURL(/#payment$/)
 await page.screenshot({path:'artifacts/documentation-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844});await page.goto('/dokumentasi.html')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
 await page.screenshot({path:'artifacts/documentation-mobile.png',fullPage:true})
 await page.getByRole('navigation',{name:'Navigasi publik'}).getByRole('link',{name:'Booking treatment'}).click();await expect(page).toHaveURL(/\/book$/)
})
test('public landing shows live services and prices and carries selections into booking',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 const response=await page.request.get('/api/public/catalog');expect(response.status()).toBe(200)
 const catalog=await response.json()
 await page.goto('/');await expect(page).toHaveURL(/\/$/)
 await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 await expect(page.getByRole('heading',{name:'Berhenti sejenak. Kembali seimbang.'})).toBeVisible()
 await expect(page.locator('.treatment-card')).toHaveCount(catalog.services.length)
 for(const service of catalog.services){
  const card=page.locator('.treatment-card').filter({has:page.getByRole('heading',{name:service.name,exact:true})})
  await expect(card).toContainText(`${service.durationMinutes} menit`)
  const fallback=service.prices.find(p=>p.locationId===null)
  const amounts=(catalog.locations.length?catalog.locations.map(l=>service.prices.find(p=>p.locationId===l.id)||fallback):[fallback]).filter(Boolean).map(p=>Number(p.price))
  if(amounts.length)await expect(card).toContainText(new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Math.min(...amounts)))
  else await expect(card).toContainText('Harga belum tersedia')
 }
 await page.screenshot({path:'artifacts/landing-desktop.png',fullPage:true})
 const location=catalog.locations[0];expect(location).toBeTruthy()
 await page.getByLabel('Area pelayanan',{exact:true}).selectOption(String(location.id))
 const service=catalog.services.find(s=>s.prices.some(p=>p.locationId===location.id||p.locationId===null));expect(service).toBeTruthy()
 const card=page.locator('.treatment-card').filter({has:page.getByRole('heading',{name:service.name,exact:true})})
 const expectedPrice=Number((service.prices.find(p=>p.locationId===location.id)||service.prices.find(p=>p.locationId===null)).price)
 await expect(card).toContainText(new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(expectedPrice))
 await card.getByRole('link',{name:'Pilih treatment'}).click()
 await expect(page.getByLabel('Treatment',{exact:true})).toHaveValue(String(service.id))
 await expect(page.getByLabel('Area pelayanan',{exact:true})).toHaveValue(String(location.id))
 await page.getByRole('link',{name:'Layanan & harga',exact:true}).click();await expect(page).toHaveURL(/\/#layanan$/)
 await page.setViewportSize({width:390,height:844});await page.goto('/')
 await expect(page.locator('.treatment-card').first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
 await page.screenshot({path:'artifacts/landing-mobile.png',fullPage:true})
 expect(errors).toEqual([])
})
test('public pricing uses area overrides and default prices without inventing zero prices',async({page})=>{
 const catalog={billing:{transportEnabled:false,taxEnabled:false},locations:[{id:101,name:'Area A'},{id:102,name:'Area B'},{id:103,name:'Area C'}],services:[
  {id:201,name:'Treatment lengkap',description:'Treatment dengan harga per area.',durationMinutes:60,prices:[{locationId:null,price:'200000'},{locationId:101,price:'175000'},{locationId:102,price:'275000'}]},
  {id:202,name:'Treatment lokal',description:'Hanya memiliki harga di Area A.',durationMinutes:90,prices:[{locationId:101,price:'120000'}]},
  {id:203,name:'Treatment tanpa harga',description:'Belum ditetapkan.',durationMinutes:60,prices:[]}
 ]}
 await page.route('**/api/public/catalog',route=>route.fulfill({json:catalog}))
 // Enter through client navigation so the browser interception also covers useFetch.
 await page.goto('/login');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 await page.getByRole('link',{name:/Ingin booking treatment/}).click()
 await expect(page.getByRole('heading',{name:'Booking treatment',exact:true})).toBeVisible()
 await page.getByRole('link',{name:'serene',exact:true}).click()
 await expect(page.locator('.treatment-card')).toHaveCount(3)
 const complete=page.locator('.treatment-card').filter({hasText:'Treatment lengkap'})
 const local=page.locator('.treatment-card').filter({hasText:'Treatment lokal'})
 const missing=page.locator('.treatment-card').filter({hasText:'Treatment tanpa harga'})
 await expect(complete).toContainText('Mulai dari');await expect(complete).toContainText('Rp 175.000')
 await expect(missing).toContainText('Harga belum tersedia');await expect(missing.getByRole('link')).toHaveCount(0)
 await expect(page.locator('.pricing-note')).not.toContainText('Biaya transport');await expect(page.locator('.pricing-note')).not.toContainText('Pajak yang berlaku')
 await page.getByLabel('Area pelayanan',{exact:true}).selectOption('102')
 await expect(complete).toContainText('Rp 275.000');await expect(local).toContainText('Harga belum tersedia');await expect(local.getByRole('link')).toHaveCount(0)
 await page.getByLabel('Area pelayanan',{exact:true}).selectOption('103');await expect(complete).toContainText('Rp 200.000')
 await page.getByLabel('Area pelayanan',{exact:true}).selectOption('101');await local.getByRole('link',{name:'Pilih treatment'}).click()
 await expect(page.getByLabel('Treatment',{exact:true})).toHaveValue('202');await expect(page.getByLabel('Area pelayanan',{exact:true})).toHaveValue('101')
 await expect(page.locator('.billing-total')).toContainText('Rp 120.000')
 await page.getByLabel('Area pelayanan',{exact:true}).selectOption('102')
 await expect(page.locator('.billing-total')).toContainText('Harga belum tersedia')
 await expect(page.getByRole('button',{name:'Kirim permintaan booking'})).toBeDisabled()
})
test('rupiah fields group thousands, validate limits, and submit numeric amounts',async({page})=>{
 await login(page);await page.goto('/services/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 const price=page.getByLabel('Harga (Rp)',{exact:true})
 await expect(price).toHaveValue('250.000')
 await price.fill('1234567,89');await expect(price).toHaveValue('1.234.567,89')
 await price.fill('');await expect(price).toHaveValue('');expect(await price.evaluate(el=>el.validity.valueMissing)).toBe(true)
 await price.fill('987654.32');await expect(price).toHaveValue('987.654,32')
 await page.getByLabel('Nama treatment').fill('Format test');await page.getByLabel('Kode layanan').fill('FORMAT-TEST')
 await page.route('**/api/services',route=>route.request().method()==='POST'?route.fulfill({status:400,json:{statusMessage:'Verifikasi format input'}}):route.continue())
 const serviceRequest=page.waitForRequest(r=>r.url().endsWith('/api/services')&&r.method()==='POST')
 await page.getByRole('button',{name:'Simpan layanan'}).click()
 expect((await serviceRequest).postDataJSON().price).toBe(987654.32)
 await page.goto('/orders/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 await page.getByLabel('Customer',{exact:true}).selectOption({index:1});await page.getByLabel('Layanan',{exact:true}).selectOption('1')
 await page.getByLabel('Alamat treatment').fill('Alamat verifikasi formatter rupiah')
 const discount=page.getByLabel('Diskon (Rp)')
 await discount.fill('-1000');expect(await discount.evaluate(el=>el.validity.customError)).toBe(true)
 await discount.fill('1000000000');expect(await discount.evaluate(el=>el.validity.customError)).toBe(true)
 await discount.fill('10000');await expect(discount).toHaveValue('10.000')
 await discount.press('Home');await discount.press('ArrowRight');await discount.pressSequentially('2');await expect(discount).toHaveValue('120.000')
 await discount.fill('10000')
 await page.getByLabel('Biaya transport (Rp)').fill('12500,50');await expect(page.getByLabel('Biaya transport (Rp)')).toHaveValue('12.500,50')
 await page.getByLabel('Pajak (Rp)').fill('3750');await expect(page.getByLabel('Pajak (Rp)')).toHaveValue('3.750')
 await page.route('**/api/orders',route=>route.request().method()==='POST'?route.fulfill({status:400,json:{statusMessage:'Verifikasi format input'}}):route.continue())
 const orderRequest=page.waitForRequest(r=>r.url().endsWith('/api/orders')&&r.method()==='POST')
 await page.getByRole('button',{name:'Buat order',exact:true}).click()
 const body=(await orderRequest).postDataJSON()
 expect(body.discount).toBe(10000);expect(body.transportFee).toBe(12500.5);expect(body.tax).toBe(3750)
})
test('owner can navigate all modules without runtime errors, desktop and mobile',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await login(page)
 await expect(page.getByRole('heading',{name:/Selamat datang/})).toBeVisible()
 await page.screenshot({path:'artifacts/dashboard.png',fullPage:true})
 for(const [path,title] of [['/orders','Orders'],['/dispatch','Dispatch board'],['/customers','Customers'],['/locations','Locations'],['/therapists','Therapists'],['/schedules','Therapist schedules'],['/services','Services & pricing'],['/payments','Payments'],['/reports','Reports & insights'],['/users','Users & roles'],['/audit','Audit log'],['/settings','Settings']]){
  await page.goto(path);await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true');await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible()
  await expect(page.locator('body')).not.toContainText('Terjadi kesalahan server')
 }
 await page.setViewportSize({width:390,height:844});await page.goto('/dashboard');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
 await expect(page.getByRole('button',{name:'Buka navigasi'})).toBeVisible()
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)
 expect(overflow).toBe(false)
 await page.getByRole('button',{name:'Buka navigasi'}).click();await expect(page.locator('.sidebar')).toHaveClass(/open/)
 expect(errors).toEqual([])
})
test('therapist has a mobile workspace and cannot enter admin routes',async({page})=>{
 await page.setViewportSize({width:390,height:844});await login(page,'ayu@serene.local')
 await expect(page.getByRole('heading',{name:/Halo, Ayu/})).toBeVisible()
 await page.screenshot({path:'artifacts/therapist-mobile.png',fullPage:true})
 await page.getByRole('link',{name:'Profil',exact:true}).click();await expect(page.getByRole('heading',{name:'Profil saya'})).toBeVisible()
 await page.goto('/users');await expect(page).toHaveURL(/\/therapist$/)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
})
test('customer, dispatch, therapist and payment workflow works through the UI',async({page,browser})=>{
 const suffix=Date.now();const name=`UI Guest ${suffix}`;let customerId;let orderId;const extraContexts=[];const paymentIds=[]
 try {
  await login(page,'cs@serene.local')
  await page.getByRole('link',{name:'Customers',exact:true}).click()
  await page.getByRole('link',{name:'Tambah customer'}).click()
  await page.getByLabel('Nama lengkap').fill(name)
  await page.getByLabel('WhatsApp / telepon').fill(`+62${String(suffix).slice(-12)}`)
  await page.getByRole('button',{name:'Simpan customer'}).click()
  await expect(page).toHaveURL(/\/customers\/\d+$/);customerId=Number(page.url().split('/').at(-1))
  await expect(page.getByRole('heading',{name:name,exact:true}).first()).toBeVisible()
  await page.getByRole('button',{name:'Tambah alamat'}).click()
  await page.getByRole('dialog').getByLabel('Label').fill('Villa')
  await page.getByRole('dialog').getByLabel('Alamat',{exact:true}).fill('Villa UI Test, Seminyak, Bali')
  await page.getByRole('dialog').getByLabel('Tautan Google Maps atau koordinat').fill('-8.6705, 115.2126')
  await page.getByRole('dialog').getByRole('button',{name:'Pasang pin',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Jadikan alamat utama').check()
  await page.getByRole('button',{name:'Simpan alamat'}).click();await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByText('Villa UI Test, Seminyak, Bali',{exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Edit customer'}).click()
  await page.getByLabel('Catatan',{exact:true}).fill('Prefers gentle pressure')
  await page.getByRole('button',{name:'Simpan customer'}).click();await expect(page.getByText('Prefers gentle pressure',{exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Buat order',exact:true}).click()
  await page.getByLabel('Customer',{exact:true}).selectOption(String(customerId))
  await expect(page.getByLabel('Alamat treatment')).toHaveValue('Villa UI Test, Seminyak, Bali')
  await expect(page.locator('.selected-location')).toContainText('-8.6705000, 115.2126000')
  await page.getByLabel('Layanan',{exact:true}).selectOption('1')
  await page.getByRole('button',{name:'Buat order',exact:true}).click()
  await expect(page).toHaveURL(/\/orders\/\d+$/);orderId=Number(page.url().split('/').at(-1))
  await expect(page.getByRole('heading',{name:name,exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Konfirmasi order'}).click()
  await expect(page.getByLabel('Lokasi',{exact:true})).toBeVisible()
  await page.getByLabel('Lokasi',{exact:true}).selectOption('1')
  await page.getByRole('button',{name:'Tetapkan lokasi'}).click()
  await expect(page.locator('.timeline')).toContainText('Diberikan ke Seminyak')
  const adminContext=await browser.newContext();extraContexts.push(adminContext);await mockMapTiles(adminContext);const adminPage=await adminContext.newPage()
  await login(adminPage,'admin@serene.local');await adminPage.goto('/orders/'+orderId);await expect(adminPage.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await adminPage.getByLabel('Therapist',{exact:true}).selectOption('1')
  await adminPage.getByRole('button',{name:'Assign therapist',exact:true}).click()
  await expect(adminPage.locator('.timeline')).toContainText('Therapist ditetapkan')
  const therapistContext=await browser.newContext({viewport:{width:390,height:844}});extraContexts.push(therapistContext);await mockMapTiles(therapistContext);const therapistPage=await therapistContext.newPage()
  const jobUrl=await adminPage.getByLabel('Tautan konfirmasi job',{exact:true}).inputValue()
  const waUrl=new URL(await adminPage.getByRole('link',{name:'Kirim melalui WhatsApp',exact:true}).getAttribute('href'))
  expect(waUrl.hostname).toBe('wa.me');expect(waUrl.searchParams.get('text')).toContain(jobUrl)
  expect(waUrl.searchParams.get('text')).not.toContain('Villa UI Test')
  await therapistPage.goto(jobUrl);await expect(therapistPage.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(therapistPage.getByRole('button',{name:'Ambil job',exact:true})).toBeVisible()
  await expect(therapistPage.getByRole('button',{name:'Tidak bisa',exact:true})).toBeVisible()
  await expect(therapistPage.locator('body')).not.toContainText(name)
  await therapistPage.screenshot({path:'artifacts/therapist-whatsapp-offer.png',fullPage:true})
  await therapistPage.getByRole('button',{name:'Ambil job',exact:true}).click()
  await expect(therapistPage.getByRole('dialog')).toBeVisible()
  await therapistPage.getByRole('button',{name:'Konfirmasi ambil job',exact:true}).click()
  await expect(therapistPage.getByRole('dialog')).not.toBeVisible()
  await expect(therapistPage.getByRole('heading',{name:name,exact:true})).toBeVisible()
  const navigationUrl=new URL(await therapistPage.getByRole('link',{name:'Buka rute di Google Maps'}).getAttribute('href'))
  expect(navigationUrl.searchParams.get('destination')).toBe('-8.6705,115.2126')
  await expect(therapistPage.getByRole('region',{name:'Peta lokasi treatment',exact:true})).toBeVisible()
  for(const label of ['Mulai perjalanan','Saya sudah tiba','Mulai treatment','Selesaikan treatment']) {
   if(label==='Selesaikan treatment'){
    const finish=therapistPage.getByRole('button',{name:label,exact:true})
    await expect(finish).toBeDisabled()
    const timer=therapistPage.getByRole('timer',{name:'Sisa durasi treatment'})
    await expect(timer).toHaveText(/00:(59|58):\d{2}|01:00:00/)
    await therapistPage.reload()
    await expect(finish).toBeDisabled();await expect(timer).toBeVisible()
    const forbidden=await therapistPage.request.post(new URL(jobUrl).pathname.replace('/job/','/api/public/jobs/')+'/action',{data:{action:'complete'}})
    expect(forbidden.status()).toBe(409)
    await elapseTreatment(orderId,4000)
    await therapistPage.reload()
    await expect(finish).toBeDisabled()
    await expect(timer).toHaveText(/00:00:0[1-4]/)
    await expect(finish).toBeEnabled({timeout:8000})
    await expect(timer).toHaveText('00:00:00')
    await therapistPage.screenshot({path:'artifacts/therapist-treatment-countdown.png',fullPage:true})
   }
   await therapistPage.getByRole('button',{name:label,exact:true}).click()
   await therapistPage.getByRole('button',{name:'Konfirmasi '+label.toLowerCase(),exact:true}).click()
   await expect(therapistPage.getByRole('dialog')).not.toBeVisible()
   await expect(therapistPage.getByRole('button',{name:label,exact:true})).not.toBeVisible()
  }
  await adminPage.reload();await expect(adminPage.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(adminPage.getByRole('button',{name:'Catat pembayaran',exact:true})).not.toBeVisible()
  await adminPage.request.post('/api/auth/logout');await login(adminPage,'owner@serene.local');await adminPage.goto('/orders/'+orderId);await expect(adminPage.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await adminPage.getByRole('button',{name:'Catat pembayaran',exact:true}).click()
  const unpaidOrder=await (await adminPage.request.get('/api/orders/'+orderId)).json()
  const balance=Number(unpaidOrder.remainingAmount)
  await expect(adminPage.getByRole('dialog').getByLabel('Jumlah (Rp)')).toHaveValue(new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(balance))
  const methodSelect=adminPage.getByRole('dialog').locator('select')
  expect(await methodSelect.locator('option').allTextContents()).toEqual(['Tunai','Transfer bank','QRIS','Kartu','Pembayaran online'])
  await methodSelect.selectOption('BANK_TRANSFER')
  const paymentRequest=adminPage.waitForRequest(r=>r.url().endsWith('/api/payments')&&r.method()==='POST')
  await adminPage.getByRole('button',{name:'Simpan pembayaran',exact:true}).click()
  expect((await paymentRequest).postDataJSON().amount).toBe(balance)
  await expect(adminPage.getByRole('dialog')).not.toBeVisible()
  paymentIds.push(...(await db.select({id:s.payments.id}).from(s.payments).where(eq(s.payments.orderId,orderId))).map(p=>p.id))
  await adminPage.getByRole('button',{name:'Tutup order',exact:true}).click()
  await expect(adminPage.locator('.timeline')).toContainText('Ditutup')
  await expect(adminPage.locator('.page-heading .badge')).toHaveText('Ditutup')
  await expect(adminPage.locator('.payment-history').filter({hasText:'Transfer bank'})).toContainText('Transfer bank')
  await adminPage.goto('/payments');await expect(adminPage.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await adminPage.getByLabel('Cari pembayaran').fill(name);await expect(adminPage.locator('tbody')).toContainText('Transfer bank');await expect(adminPage.locator('tbody')).not.toContainText('BANK_TRANSFER')
 } finally {
  for(const context of extraContexts)await context.close()
  if(paymentIds.length)await db.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'payments' and ${inArray(s.auditLogs.entityId,paymentIds)}`)
  if(orderId)await db.transaction(async tx=>{await tx.delete(s.notifications).where(sql`${s.notifications.data}->>'orderId' = ${String(orderId)}`);for(const table of [s.orderStatusLogs,s.orderAssignments,s.orderItems,s.payments])await tx.delete(table).where(eq(table.orderId,orderId));await tx.delete(s.orders).where(eq(s.orders.id,orderId));await tx.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'orders' and ${s.auditLogs.entityId} = ${orderId}`)})
  if(customerId){const addressIds=(await db.select({id:s.customerAddresses.id}).from(s.customerAddresses).where(eq(s.customerAddresses.customerId,customerId))).map(a=>a.id);if(addressIds.length)await db.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'customer_addresses' and ${inArray(s.auditLogs.entityId,addressIds)}`);await db.delete(s.customerAddresses).where(eq(s.customerAddresses.customerId,customerId));await db.delete(s.customers).where(eq(s.customers.id,customerId));await db.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'customers' and ${s.auditLogs.entityId} = ${customerId}`)}
 }
})

test('public booking selects, moves and clears a pin, handles GPS, and persists the chosen destination',async({page,context})=>{
 const suffix=Date.now();let orderId;let customerId
 const name=`Public Map Guest ${suffix}`
 const phone=`+62${String(suffix).slice(-12)}`
 try {
  await context.setGeolocation({latitude:-8.6705,longitude:115.2126})
  await page.goto('/book')
  await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  const map=page.getByRole('region',{name:'Peta untuk memilih pin lokasi treatment',exact:true})
  await expect(map.locator('.leaflet-control-zoom')).toBeVisible()
  await expect(page.getByText('Belum ada pin dipilih.',{exact:false})).toBeVisible()
  await map.click({position:{x:160,y:125}})
  await expect(page.locator('.selected-location')).toBeVisible()
  const marker=map.locator('.leaflet-marker-icon')
  const previousCoordinates=await page.locator('.selected-location small').textContent()
  const box=await marker.boundingBox()
  await page.mouse.move(box.x+15,box.y+15);await page.mouse.down();await page.mouse.move(box.x+50,box.y+35,{steps:6});await page.mouse.up()
  await expect(page.locator('.selected-location small')).not.toHaveText(previousCoordinates)
  await page.getByRole('button',{name:'Hapus pin',exact:true}).click()
  await expect(page.locator('.selected-location')).not.toBeVisible()
  await page.getByLabel('Tautan Google Maps atau koordinat').fill('https://maps.app.goo.gl/example')
  await page.getByRole('button',{name:'Pasang pin',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('tautan Google Maps lengkap')
  await page.getByRole('button',{name:'Gunakan lokasi saya',exact:true}).click()
  await expect(page.locator('.location-message')).toContainText('Izin lokasi belum diberikan')
  await context.grantPermissions(['geolocation'],{origin:'http://localhost:3000'})
  await page.getByRole('button',{name:'Gunakan lokasi saya',exact:true}).click()
  await expect(page.locator('.selected-location')).toContainText('-8.6705000, 115.2126000')
  await page.getByLabel('Tautan Google Maps atau koordinat').fill('https://www.google.com/maps/search/?api=1&query=-8.6712345%2C115.2134567')
  await page.getByRole('button',{name:'Pasang pin',exact:true}).click()
  await expect(page.locator('.selected-location')).toContainText('-8.6712345, 115.2134567')
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
  await page.getByLabel('Nama lengkap').fill(name)
  await page.getByLabel('WhatsApp',{exact:true}).fill(phone)
  await page.getByRole('combobox',{name:'Treatment',exact:true}).selectOption('1')
  await page.getByLabel('Hotel / villa & alamat').fill('Villa Maps Test, Bali')
  await page.screenshot({path:'artifacts/customer-booking-pin.png',fullPage:true})
  await page.getByRole('button',{name:'Kirim permintaan booking',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Booking diterima.',exact:true})).toBeVisible()
  const orderNumber=await page.locator('.booking-number').textContent()
  const [order]=await db.select().from(s.orders).where(eq(s.orders.orderNumber,orderNumber))
  orderId=order.id;customerId=order.customerId
  expect(Number(order.latitude)).toBe(-8.6712345);expect(Number(order.longitude)).toBe(115.2134567)
 } finally {
  // Recover this run's records even if the success UI assertion failed after submit.
  if(!customerId){const [customer]=await db.select().from(s.customers).where(eq(s.customers.phone,phone));if(customer){customerId=customer.id;const [order]=await db.select().from(s.orders).where(eq(s.orders.customerId,customerId));orderId=order?.id}}
  if(orderId)await db.transaction(async tx=>{await tx.delete(s.notifications).where(sql`${s.notifications.data}->>'orderId' = ${String(orderId)}`);for(const table of [s.orderStatusLogs,s.orderAssignments,s.orderItems,s.payments])await tx.delete(table).where(eq(table.orderId,orderId));await tx.delete(s.orders).where(eq(s.orders.id,orderId));await tx.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'orders' and ${s.auditLogs.entityId} = ${orderId}`)})
  if(customerId)await db.delete(s.customers).where(eq(s.customers.id,customerId))
 }
})

test('WhatsApp job page handles link replacement, rejection and expiry without a therapist login',async({page,browser})=>{
 const suffix=Date.now();let customerId;let orderId;let therapistContext
 try {
  await login(page)
  const customerResponse=await page.request.post('/api/customers',{data:{name:`WA UI Guest ${suffix}`,phone:`+627${String(suffix).slice(-11)}`}})
  expect(customerResponse.ok()).toBe(true);customerId=(await customerResponse.json()).id
  const date=new Date(Date.now()+12*86400000).toISOString().slice(0,10)
  const response=await page.request.post('/api/orders',{data:{customerId,locationId:1,bookingDate:date,bookingTime:'10:00',address:'Private WA test villa',services:[{serviceId:1,qty:1}]}})
  expect(response.ok()).toBe(true);orderId=(await response.json()).id
  for(const [action,data] of [['confirm',{}],['assign-location',{locationId:1}],['assign-therapist',{therapistId:1}]])expect((await page.request.post(`/api/orders/${orderId}/${action}`,{data})).ok()).toBe(true)
  await page.goto(`/orders/${orderId}`)
  await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await page.getByRole('button',{name:'Buat ulang tautan WhatsApp',exact:true}).click()
  await page.getByRole('button',{name:'Buat dan ganti tautan',exact:true}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const oldUrl=await page.getByLabel('Tautan konfirmasi job',{exact:true}).inputValue()
  therapistContext=await browser.newContext({viewport:{width:390,height:844}});await mockMapTiles(therapistContext);const therapistPage=await therapistContext.newPage()
  await therapistPage.goto(oldUrl);await expect(therapistPage.getByRole('button',{name:'Ambil job',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Buat ulang tautan WhatsApp',exact:true}).click()
  await page.getByRole('combobox',{name:'Masa respons'}).selectOption('15')
  await page.getByRole('button',{name:'Buat dan ganti tautan',exact:true}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const newUrl=await page.getByLabel('Tautan konfirmasi job',{exact:true}).inputValue();expect(newUrl).not.toBe(oldUrl)
  await therapistPage.reload();await expect(therapistPage.getByRole('heading',{name:'Tautan sudah tidak berlaku',exact:true})).toBeVisible()
  await therapistPage.goto(newUrl)
  await therapistPage.getByRole('button',{name:'Tidak bisa',exact:true}).click()
  await therapistPage.getByLabel('Alasan tidak bisa',{exact:true}).fill('Tidak ada kendaraan')
  await therapistPage.getByRole('button',{name:'Konfirmasi tidak bisa',exact:true}).click()
  await expect(therapistPage.getByRole('heading',{name:'Job sudah ditolak',exact:true})).toBeVisible()
  await page.reload();await expect(page.locator('.timeline')).toContainText('Tidak ada kendaraan')
  const assignResponse=await page.request.post(`/api/orders/${orderId}/assign-therapist`,{data:{therapistId:1}});expect(assignResponse.ok()).toBe(true)
  const next=(await assignResponse.json()).jobLink
  await db.update(s.therapistJobLinks).set({offerExpiresAt:new Date(Date.now()-60000)}).where(eq(s.therapistJobLinks.assignmentId,next.assignmentId))
  await therapistPage.goto(next.url);await expect(therapistPage.getByRole('heading',{name:'Penawaran kedaluwarsa',exact:true})).toBeVisible()
  await expect(therapistPage.getByRole('button',{name:'Ambil job',exact:true})).not.toBeVisible()
  expect(await therapistPage.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
  await page.reload();await expect(page.locator('.timeline')).toContainText('Penawaran WhatsApp kedaluwarsa')
 } finally {
  await therapistContext?.close()
  if(orderId)await db.transaction(async tx=>{await tx.delete(s.notifications).where(sql`${s.notifications.data}->>'orderId' = ${String(orderId)}`);for(const table of [s.orderStatusLogs,s.orderAssignments,s.orderItems])await tx.delete(table).where(eq(table.orderId,orderId));await tx.delete(s.orders).where(eq(s.orders.id,orderId));await tx.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'orders' and ${s.auditLogs.entityId} = ${orderId}`)})
  if(customerId){await db.delete(s.customers).where(eq(s.customers.id,customerId));await db.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'customers' and ${s.auditLogs.entityId} = ${customerId}`)}
 }
})

test.afterAll(async()=>{await pool.end()})

test('owner can change revenue formula and invalid totals cannot be saved',async({page})=>{
 await login(page)
 const response=await page.request.get('/api/settings/revenue-sharing');const original=await response.json()
 try {
  await page.goto('/settings');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true');await expect(page.getByRole('heading',{name:'Pembagian pendapatan',exact:true})).toBeVisible()
  await page.getByLabel('Owner (%)',{exact:true}).fill('20')
  await expect(page.getByRole('button',{name:'Simpan pengaturan'})).toBeDisabled()
  await page.getByLabel('Admin (%)',{exact:true}).fill('15');await page.getByLabel('Therapist (%)',{exact:true}).fill('65')
  await page.getByLabel('Waktu pembagian').selectOption('ORDER_COMPLETED')
  await expect(page.getByRole('button',{name:'Simpan pengaturan'})).toBeEnabled()
  const saved=page.waitForResponse(r=>r.url().endsWith('/api/settings/revenue-sharing')&&r.request().method()==='PATCH')
  await page.getByRole('button',{name:'Simpan pengaturan'}).click();expect((await saved).status()).toBe(200)
  await page.reload();await expect(page.getByLabel('Owner (%)',{exact:true})).toHaveValue('20');await expect(page.getByLabel('Waktu pembagian')).toHaveValue('ORDER_COMPLETED')
  await page.screenshot({path:'artifacts/revenue-sharing-settings.png',fullPage:true})
  await page.setViewportSize({width:390,height:844});await expect(page.getByRole('button',{name:'Simpan pengaturan'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
 }finally{
  const restored=await page.request.patch('/api/settings/revenue-sharing',{data:{ownerPercent:Number(original.ownerPercent),adminPercent:Number(original.adminPercent),therapistPercent:Number(original.therapistPercent),trigger:original.trigger}});expect(restored.status()).toBe(200)
 }
})

test('transport and tax settings persist and control order and booking displays',async({page})=>{
 await login(page)
 const response=await page.request.get('/api/settings/billing');const original=await response.json()
 async function saveBilling() {const saved=page.waitForResponse(r=>r.url().endsWith('/api/settings/billing')&&r.request().method()==='PATCH');await page.getByRole('button',{name:'Simpan transport dan pajak'}).click();expect((await saved).status()).toBe(200)}
 try {
  await page.goto('/settings');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await page.getByRole('switch',{name:/Aktifkan biaya transport/}).uncheck();await page.getByRole('switch',{name:/Aktifkan pajak/}).uncheck();await saveBilling()
  await page.reload();await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(page.getByRole('switch',{name:/Aktifkan biaya transport/})).not.toBeChecked();await expect(page.getByRole('switch',{name:/Aktifkan pajak/})).not.toBeChecked()
  await page.screenshot({path:'artifacts/billing-settings.png',fullPage:true})
  await page.goto('/orders/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(page.getByLabel('Biaya transport (Rp)')).not.toBeVisible();await expect(page.getByLabel('Pajak (Rp)')).not.toBeVisible()
  await page.goto('/book');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(page.getByText('Biaya transport akan dikonfirmasi oleh tim.')).not.toBeVisible();await expect(page.getByText('Pajak yang berlaku akan dikonfirmasi oleh tim.')).not.toBeVisible()
  await page.goto('/settings');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await page.getByRole('switch',{name:/Aktifkan biaya transport/}).check();await saveBilling()
  await page.goto('/orders/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(page.getByLabel('Biaya transport (Rp)')).toBeVisible();await expect(page.getByLabel('Pajak (Rp)')).not.toBeVisible()
  await page.goto('/settings');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await page.getByRole('switch',{name:/Aktifkan biaya transport/}).uncheck();await page.getByRole('switch',{name:/Aktifkan pajak/}).check();await saveBilling()
  await page.goto('/orders/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await expect(page.getByLabel('Biaya transport (Rp)')).not.toBeVisible();await expect(page.getByLabel('Pajak (Rp)')).toBeVisible()
 }finally{expect((await page.request.patch('/api/settings/billing',{data:original})).status()).toBe(200)}
})

test('location admin has an operational dashboard and manages only local orders and therapists',async({page})=>{
 let therapistId,accountId,customerId,orderId
 const suffix=Date.now(),name=`Admin UI Therapist ${suffix}`,guest=`Admin UI Guest ${suffix}`
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 try{
  await login(page,'admin@serene.local');await expect(page.getByRole('heading',{name:'Dashboard admin',exact:true})).toBeVisible()
  expect(await page.locator('.sidebar nav a').evaluateAll(links=>links.map(a=>new URL(a.href).pathname))).toEqual(['/dashboard','/orders','/therapists'])
  await expect(page.getByRole('heading',{name:'Revenue overview'})).not.toBeVisible();await expect(page.locator('.main-content')).not.toContainText('Rp')
  await page.screenshot({path:'artifacts/admin-dashboard.png',fullPage:true})
  for(const path of ['/customers','/locations','/services','/schedules','/payments','/reports','/users','/audit','/settings']){await page.goto(path);await expect(page).toHaveURL(/\/dashboard$/)}
  const opts=await (await page.request.get('/api/therapists/options')).json();const location=opts.locations[0]
  await page.goto('/therapists/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await page.getByLabel('Nama lengkap').fill(name);await page.getByLabel('Email login').fill(`admin-ui-${suffix}@test.local`);await page.getByLabel('Password akun').fill(password);await page.getByLabel('Kode karyawan').fill(`ADMUI-${suffix}`);await page.getByRole('checkbox',{name:location.name,exact:true}).check()
  await page.getByRole('button',{name:'Simpan therapist',exact:true}).click();await expect(page).toHaveURL(/\/therapists\/\d+$/);therapistId=Number(page.url().split('/').at(-1))
  const profile=await (await page.request.get('/api/therapists/'+therapistId)).json();accountId=profile.userId
  await expect(page.getByRole('heading',{name:'Jadwal therapist',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tambah jadwal',exact:true}).click()
  const date=new Date(Date.now()+47*86400000).toISOString().slice(0,10)
  await page.getByRole('dialog').getByLabel('Tanggal jadwal').fill(date);await page.getByRole('button',{name:'Simpan jadwal',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.goto('/orders/new');await expect(page.locator('[data-app-ready]')).toHaveAttribute('data-app-ready','true')
  await page.getByRole('button',{name:'Tambah customer baru',exact:true}).click();await page.getByRole('dialog').getByLabel('Nama customer').fill(guest);await page.getByRole('dialog').getByLabel('WhatsApp customer').fill(`+625${String(suffix).slice(-11)}`)
  await page.getByRole('button',{name:'Simpan customer untuk order'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();customerId=Number(await page.getByLabel('Customer',{exact:true}).inputValue())
  await page.getByLabel('Alamat treatment').fill('Admin UI local villa');await page.getByLabel('Tanggal',{exact:true}).fill(date);await page.getByLabel('Waktu mulai').fill('10:00');await page.getByLabel('Layanan',{exact:true}).selectOption('1')
  await page.getByRole('button',{name:'Buat order',exact:true}).click();await expect(page).toHaveURL(/\/orders\/\d+$/);orderId=Number(page.url().split('/').at(-1))
  await page.getByRole('button',{name:'Konfirmasi order'}).click();await page.getByLabel('Lokasi',{exact:true}).selectOption(String(location.id));await page.getByRole('button',{name:'Tetapkan lokasi'}).click();await page.getByLabel('Therapist',{exact:true}).selectOption(String(therapistId));await page.getByRole('button',{name:'Assign therapist',exact:true}).click()
  await expect(page.locator('.page-heading .badge')).toHaveText('Menunggu respons');await expect(page.getByRole('button',{name:'Catat pembayaran'})).not.toBeVisible();await expect(page.getByRole('heading',{name:'Pembagian pendapatan'})).not.toBeVisible()
  expect((await page.request.get('/api/reports')).status()).toBe(403)
  await page.goto('/dashboard');await page.setViewportSize({width:390,height:844});await expect(page.getByRole('heading',{name:'Dashboard admin',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false)
  expect(errors).toEqual([])
 }finally{
  if(orderId)await db.transaction(async tx=>{await tx.delete(s.notifications).where(sql`${s.notifications.data}->>'orderId' = ${String(orderId)}`);for(const table of [s.orderStatusLogs,s.orderAssignments,s.orderItems,s.payments])await tx.delete(table).where(eq(table.orderId,orderId));await tx.delete(s.orders).where(eq(s.orders.id,orderId));await tx.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'orders' and ${s.auditLogs.entityId} = ${orderId}`)})
  if(customerId){await db.delete(s.customers).where(eq(s.customers.id,customerId));await db.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'customers' and ${s.auditLogs.entityId} = ${customerId}`)}
  if(therapistId){await db.delete(s.therapistSchedules).where(eq(s.therapistSchedules.therapistId,therapistId));await db.delete(s.therapistLocations).where(eq(s.therapistLocations.therapistId,therapistId));await db.delete(s.therapists).where(eq(s.therapists.id,therapistId));await db.delete(s.auditLogs).where(sql`${s.auditLogs.entity} = 'therapists' and ${s.auditLogs.entityId} = ${therapistId}`)}
  if(accountId){await db.delete(s.notifications).where(eq(s.notifications.userId,accountId));await db.delete(s.userRoles).where(eq(s.userRoles.userId,accountId));await db.delete(s.users).where(eq(s.users.id,accountId))}
 }
})
