import { z } from 'zod'
import { ROLES, SOURCES, PAYMENT_METHODS } from '../constants/index.js'
const name = z.string().trim().min(2).max(150)
const notes = z.string().trim().max(2000).optional().default('')
export const identifier = z.coerce.number().int().positive()
const phone = z.string().trim().regex(/^\+?[0-9 -]{8,25}$/, 'Nomor telepon tidak valid').transform(v => v.replace(/[ -]/g, ''))
const email = z.union([z.email(), z.literal('')]).optional().transform(v => v || null)
const amount = z.coerce.number().min(0).max(1000000000).refine(v => Math.abs(v * 100 - Math.round(v * 100)) < 0.0001, 'Maksimal 2 desimal')
export const date = z.iso.date()
export const clock = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)
export const loginSchema = z.object({ email: z.email().transform(v => v.toLowerCase()), password: z.string().min(1).max(200) }).strict()
export const customerSchema = z.object({ name, phone, email, notes }).strict()
const coordinate = (limit) => z.preprocess(v => v === null || (typeof v === 'string' && !v.trim()) ? undefined : v, z.union([z.number(), z.string().trim().regex(/^-?\d+(?:\.\d+)?$/).transform(Number)]).pipe(z.number().min(-limit).max(limit)).optional())
export const coordinatePair = (v) => (v.latitude === undefined) === (v.longitude === undefined)
const coordinateMessage = { message: 'Latitude dan longitude harus diisi bersama', path: ['latitude'] }
export const addressSchema = z.object({ label: name, address: z.string().trim().min(3).max(2000), notes, isDefault: z.boolean().default(false), latitude: coordinate(90), longitude: coordinate(180) }).strict().refine(coordinatePair, coordinateMessage)
export const locationSchema = z.object({ name, code: z.string().trim().min(2).max(50).transform(v => v.toUpperCase()), phone: z.string().max(50).optional().default(''), address: notes, timezone: z.string().refine(v => { try { new Intl.DateTimeFormat('en', { timeZone: v }); return true } catch { return false } }).default('Asia/Makassar'), isActive: z.boolean().default(true) }).strict()
export const serviceSchema = z.object({ name, code: z.string().trim().min(2).max(50).transform(v => v.toUpperCase()), description: notes, durationMinutes: z.coerce.number().int().min(15).max(480), price: amount, locationId: identifier.nullable().optional().default(null), isActive: z.boolean().default(true) }).strict()
export const userSchema = z.object({ name, email: z.email().transform(v => v.toLowerCase()), phone: z.string().max(50).optional(), password: z.string().min(10).max(128), role: z.enum(ROLES), locationId: identifier.nullable().optional().default(null), isActive: z.boolean().default(true) }).strict().refine(v => v.role !== 'LOCATION_ADMIN' || v.locationId, 'Admin lokasi wajib memiliki lokasi')
export const therapistSchema = z.object({ name, email: z.email().transform(v => v.toLowerCase()), phone: z.string().max(50).optional().default(''), password: z.string().min(10).max(128).optional(), employeeCode: z.string().trim().min(2).max(50), gender: z.enum(['FEMALE', 'MALE', '']).optional().default(''), notes, locationIds: z.array(identifier).min(1), isActive: z.boolean().default(true) }).strict()
export const scheduleSchema = z.object({ therapistId: identifier, locationId: identifier, scheduleDate: date, startTime: clock, endTime: clock, status: z.enum(['AVAILABLE', 'BOOKED', 'OFF', 'LEAVE']), notes }).strict().refine(v => v.endTime > v.startTime, 'Jam selesai harus setelah jam mulai')
export const orderFieldsSchema = z.object({ customerId: identifier, customerAddressId: identifier.nullable().optional(), locationId: identifier.nullable().default(null), bookingDate: date, bookingTime: clock, address: z.string().trim().min(3).max(2000), latitude: coordinate(90), longitude: coordinate(180), services: z.array(z.object({ serviceId: identifier, qty: z.coerce.number().int().min(1).max(10) }).strict()).min(1).max(20), discount: amount.default(0), transportFee: amount.default(0), tax: amount.default(0), source: z.enum(SOURCES).default('WHATSAPP'), notes }).strict()
export const orderSchema = orderFieldsSchema.refine(coordinatePair, coordinateMessage)
export const publicBookingSchema = orderFieldsSchema.pick({ bookingDate: true, bookingTime: true, address: true, services: true, locationId: true, notes: true, latitude: true, longitude: true }).extend({ name, phone }).strict().refine(coordinatePair, coordinateMessage)
export const paymentSchema = z.object({ orderId: identifier, amount: amount.refine(v => v > 0, 'Jumlah harus lebih dari 0'), paymentMethod: z.enum(PAYMENT_METHODS), paymentReference: z.string().trim().max(200).optional().default('') }).strict()
export const assignmentSchema = z.object({ therapistId: identifier }).strict()
export const jobLinkSchema = z.object({ minutes: z.number().int().min(5).max(120).default(30) }).strict()
export const jobActionSchema = z.object({ action: z.enum(['accept', 'reject', 'on-the-way', 'arrived', 'start', 'complete']), notes: z.string().trim().max(500).optional().default('') }).strict().refine(v => v.action !== 'reject' || v.notes.length >= 3, 'Isi alasan penolakan minimal 3 karakter')
export const locationAssignmentSchema = z.object({ locationId: identifier }).strict()
export const reasonSchema = z.object({ notes: z.string().trim().min(3).max(2000) }).strict()
const percent = z.coerce.number().min(0).max(100).refine(v => Math.abs(v * 100 - Math.round(v * 100)) < 0.0001, 'Maksimal 2 desimal')
export const revenueSharingSchema = z.object({ ownerPercent: percent, adminPercent: percent, therapistPercent: percent, trigger: z.enum(['PAYMENT_RECEIVED', 'ORDER_COMPLETED']) }).strict().refine(v => Math.round(v.ownerPercent * 100) + Math.round(v.adminPercent * 100) + Math.round(v.therapistPercent * 100) === 10000, 'Total pembagian harus tepat 100%')
export const billingSettingsSchema = z.object({ transportEnabled: z.boolean(), taxEnabled: z.boolean() }).strict()
