<script setup>
import { STATUSES, STATUS_LABELS, SOURCES } from '#shared/constants/index.js'
import { today } from '#shared/utils/format.js'
const { canManageOrders, isLocationAdmin } = useAuth()
const filters = reactive({ date:'',locationId:'',status:'',therapistId:'',paymentStatus:'',source:'',search:'' })
const query = computed(() => Object.fromEntries(Object.entries(filters).filter(([,v]) => v !== '')))
const { data: orders, refresh, error } = await useOrders(query)
const { data: locations } = await useFetch(isLocationAdmin.value?'/api/orders/options':'/api/locations',{default:()=>[]})
const { data: therapists } = await useFetch('/api/therapists',{default:()=>[]})
const page = ref(1); watch(query,()=>page.value=1)
const rows = computed(()=>orders.value.slice((page.value-1)*10,page.value*10))
usePolling(refresh)
function reset() { Object.keys(filters).forEach(k=>filters[k]='') }
</script><template><div><LayoutPageHeader title="Orders" description="Kelola setiap booking, dari percakapan pertama hingga pelayanan selesai." eyebrow="OPERATIONS"><UiButton v-if="canManageOrders" to="/orders/new"><UiIcon name="plus" :size="17" />Buat order</UiButton></LayoutPageHeader><div class="summary-tabs"><button :class="{active:!filters.status}" @click="filters.status=''">Semua orders <span class="count">{{ orders.length }}</span></button><button @click="filters.status='NEW'" :class="{active:filters.status==='NEW'}">Baru</button><button @click="filters.status='ASSIGNED_LOCATION'" :class="{active:filters.status==='ASSIGNED_LOCATION'}">Menunggu assignment</button><button @click="filters.status='IN_PROGRESS'" :class="{active:filters.status==='IN_PROGRESS'}">Sedang berjalan</button><button @click="filters.status='CLOSED'" :class="{active:filters.status==='CLOSED'}">Selesai</button></div><section class="panel"><div class="filter-bar"><div class="search-control"><UiIcon name="search" :size="17" /><input v-model="filters.search" placeholder="Cari customer atau nomor order…" aria-label="Cari orders" /></div><input v-model="filters.date" type="date" aria-label="Filter tanggal" /><select v-model="filters.locationId" aria-label="Filter lokasi"><option value="">Semua lokasi</option><option v-for="l in (isLocationAdmin?locations?.locations||[]:locations)" :key="l.id" :value="l.id">{{ l.name }}</option></select><select v-model="filters.status" aria-label="Filter status"><option value="">Semua status</option><option v-for="s in STATUSES" :key="s" :value="s">{{ STATUS_LABELS[s] }}</option></select><button class="icon-button" aria-label="Reset filter" @click="reset"><UiIcon name="refresh" :size="17" /></button></div><div class="filter-bar secondary"><select v-model="filters.therapistId" aria-label="Filter therapist"><option value="">Semua therapist</option><option v-for="t in therapists" :key="t.id" :value="t.id">{{ t.name }}</option></select><select v-model="filters.paymentStatus" aria-label="Filter pembayaran"><option value="">Semua pembayaran</option><option v-for="s in ['UNPAID','PARTIAL','PAID','REFUNDED']" :key="s" :value="s">{{ STATUS_LABELS[s] }}</option></select><select v-model="filters.source" aria-label="Filter sumber"><option value="">Semua sumber</option><option v-for="s in SOURCES" :key="s" :value="s">{{ s }}</option></select></div><p v-if="error" class="error-message">{{ error.data?.statusMessage }} <button @click="refresh">Coba lagi</button></p><OrderTable :orders="rows" /><UiPagination v-model:page="page" :total="orders.length" /></section></div></template>